<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PersonalHub.Application\PersonalHub.Application.csproj" />
    <ProjectReference Include="..\PersonalHub.Domain\PersonalHub.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" />
	</ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
